name: Coverage
on: [push]
permissions: read-all
jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
        - linux-amd64-coverage
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: "1.19.5"
    - env:
        TARGET: ${{ matrix.target }}
      run: |
        mkdir "${TARGET}"
        case "${TARGET}" in
          linux-amd64-coverage)
            GOARCH=amd64 ./scripts/codecov_upload.sh
            ;;
          *)
            echo "Failed to find target"
            exit 1
            ;;
        esac
