name: Coverage
on: [push]
permissions: read-all
jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
        - linux-amd64-coverage
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        go-version: "1.19.5"
    - env:
        TARGET: ${{ matrix.target }}
      run: |
        mkdir "${TARGET}"
        case "${TARGET}" in
          linux-amd64-coverage)
            GOARCH=amd64 ./scripts/codecov_upload.sh
            ;;
          *)
            echo "Failed to find target"
            exit 1
            ;;
        esac
