name: E2E-arm64
on:
  schedule:
    - cron: '0 1 * * *' # runs daily at 1am.
permissions: read-all
jobs:
  test:
    runs-on: [Linux, ARM64]
    strategy:
      fail-fast: true
      matrix:
        target:
        - linux-arm64-e2e
    steps:
    - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        ref: main
        go-version: "1.19.5"
    - run: date
    - env:
        TARGET: ${{ matrix.target }}
      run: |
        echo "${TARGET}"
        case "${TARGET}" in
          linux-arm64-e2e)
            PASSES='build release e2e' CPU='4' EXPECT_DEBUG='true' COVER='false' RACE='true' ./scripts/test.sh 2>&1 | tee test.log
            ! grep -E "(--- FAIL:|FAIL:|DATA RACE|panic: test timed out|appears to have leaked)" -B50 -A10 test.log
            ;;
          *)
            echo "Failed to find target"
            exit 1
            ;;
        esac
